#!/usr/bin/env bash
# 04_sudo.sh — sudo hardening
# locks down sudoers defaults, creates scoped rules for deploy user,
# and enables sudo logging to its own file
set -euo pipefail

run() {
    if [[ "${DRY_RUN}" == true ]]; then
        log DRY "would run: $*"
    else
        "$@"
    fi
}

SUDOERS_DIR="/etc/sudoers.d"
DEPLOY_SUDOERS="${SUDOERS_DIR}/10-${DEPLOY_USER}-hardened"

# make sure the existing sudoers is sane before we touch anything
if [[ "${DRY_RUN}" == false ]]; then
    if ! visudo -c -f /etc/sudoers > /dev/null 2>&1; then
        log ERROR "sudo: /etc/sudoers has syntax errors — fix manually before running this module"
        exit 1
    fi
    log INFO "sudo: /etc/sudoers syntax ok"
fi

SUDOERS_DEFAULTS="${SUDOERS_DIR}/00-hardened-defaults"
if [[ "${DRY_RUN}" == false ]]; then
    cat > "${SUDOERS_DEFAULTS}" <<'EOF'
# sudo defaults — hardened by harden.sh

# log all sudo commands to syslog and a dedicated file
Defaults syslog=auth
# note: log_input captures stdin, which can include passwords piped into commands.
# disable it if that's a concern for your workflow.
Defaults log_input, log_output
Defaults logfile="/var/log/sudo.log"

# require password on every sudo call — no cached token
Defaults timestamp_timeout=0

# warn on bad password attempts
Defaults mail_badpass

# show a notice on first use
Defaults lecture=always
Defaults lecture_file=/etc/sudoers.d/sudo-lecture

# clean environment — prevent ld_preload and similar tricks
Defaults env_reset
Defaults env_delete+="LD_PRELOAD LD_LIBRARY_PATH LD_* DYLD_*"
Defaults secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
EOF

    cat > /etc/sudoers.d/sudo-lecture <<'EOF'
#
# notice: this server is monitored. all sudo commands are logged.
#
EOF

    if visudo -c -f "${SUDOERS_DEFAULTS}" > /dev/null 2>&1; then
        chmod 0440 "${SUDOERS_DEFAULTS}"
        chmod 0440 /etc/sudoers.d/sudo-lecture
        log INFO "sudo: hardened defaults applied at ${SUDOERS_DEFAULTS}"
    else
        log ERROR "sudo: defaults file has syntax errors — skipping"
        rm -f "${SUDOERS_DEFAULTS}"
        exit 1
    fi
else
    log DRY "would create hardened sudo defaults at ${SUDOERS_DEFAULTS}"
fi

if [[ "${DRY_RUN}" == false ]]; then
    cat > "${DEPLOY_SUDOERS}" <<EOF
# sudo rules for ${DEPLOY_USER} — generated by harden.sh on $(date '+%Y-%m-%d')

# full sudo with password required every time (timestamp_timeout=0 above)
${DEPLOY_USER} ALL=(ALL:ALL) ALL

# passwordless restarts for specific services — add more as needed
${DEPLOY_USER} ALL=(root) NOPASSWD: /bin/systemctl restart nginx
${DEPLOY_USER} ALL=(root) NOPASSWD: /bin/systemctl reload nginx
${DEPLOY_USER} ALL=(root) NOPASSWD: /bin/systemctl restart myapp
${DEPLOY_USER} ALL=(root) NOPASSWD: /usr/bin/certbot renew

# block shell escalation — even with the password above, can't sudo into a shell
${DEPLOY_USER} ALL=(ALL) !/bin/bash
${DEPLOY_USER} ALL=(ALL) !/bin/sh
${DEPLOY_USER} ALL=(ALL) !/bin/dash
${DEPLOY_USER} ALL=(ALL) !/usr/bin/passwd root
EOF

    if visudo -c -f "${DEPLOY_SUDOERS}" > /dev/null 2>&1; then
        chmod 0440 "${DEPLOY_SUDOERS}"
        log INFO "sudo: deploy user rules applied at ${DEPLOY_SUDOERS}"
    else
        log ERROR "sudo: deploy sudoers file has syntax errors"
        rm -f "${DEPLOY_SUDOERS}"
        exit 1
    fi
else
    log DRY "would create scoped sudoers for ${DEPLOY_USER} at ${DEPLOY_SUDOERS}"
fi

if [[ "${DRY_RUN}" == false ]]; then
    touch /var/log/sudo.log
    chmod 600 /var/log/sudo.log
    chown root:root /var/log/sudo.log
    log INFO "sudo: log file created at /var/log/sudo.log"
else
    log DRY "would create /var/log/sudo.log"
fi

if [[ "${DRY_RUN}" == false ]]; then
    log INFO "sudo: rules for ${DEPLOY_USER}:"
    sudo -l -U "${DEPLOY_USER}" 2>&1 | while IFS= read -r line; do
        log INFO "  ${line}"
    done
fi

echo "scoped rules, logging enabled, shell escalation blocked" > /tmp/harden_note_sudo

log INFO "sudo hardening complete"
