#!/usr/bin/env bash
# 08_logging.sh — system logging hardening
# hardens log file permissions, extends retention, enables process accounting
# and auditd with watch rules on critical files
set -euo pipefail

run() {
    if [[ "${DRY_RUN}" == true ]]; then
        log DRY "would run: $*"
    else
        "$@"
    fi
}

# log file permissions

log INFO "logging: hardening log file permissions..."

harden_log() {
    local path="$1" mode="$2" owner="${3:-root:adm}"
    if [[ -f "${path}" ]]; then
        if [[ "${DRY_RUN}" == false ]]; then
            chmod "${mode}" "${path}"
            chown "${owner}" "${path}"
        else
            log DRY "would chmod ${mode} chown ${owner} ${path}"
        fi
        log INFO "logging: ${mode} ${owner} → ${path}"
    fi
}

harden_log /var/log/auth.log       640 root:adm
harden_log /var/log/syslog         640 root:adm
harden_log /var/log/kern.log       640 root:adm
harden_log /var/log/daemon.log     640 root:adm
harden_log /var/log/cron.log       640 root:adm
harden_log /var/log/mail.log       640 root:adm
harden_log /var/log/ufw.log        640 root:adm
harden_log /var/log/fail2ban.log   640 root:adm

if [[ "${DRY_RUN}" == false ]]; then
    chmod 750 /var/log
    log INFO "logging: /var/log set to 750"
fi

# logrotate

log INFO "logging: setting log retention to ${LOG_ROTATE_WEEKS:-52} weeks..."

LOGROTATE_CONF="/etc/logrotate.conf"
if [[ "${DRY_RUN}" == false ]]; then
    [[ -f "${LOGROTATE_CONF}" ]] && cp "${LOGROTATE_CONF}" "${LOGROTATE_CONF}.bak"

    sed -i "s/^rotate .*/rotate ${LOG_ROTATE_WEEKS:-52}/" "${LOGROTATE_CONF}"

    if ! grep -q "^compress" "${LOGROTATE_CONF}"; then
        sed -i '/^weekly/a compress' "${LOGROTATE_CONF}"
    fi

    if ! grep -q "^delaycompress" "${LOGROTATE_CONF}"; then
        sed -i '/^compress/a delaycompress' "${LOGROTATE_CONF}"
    fi

    log INFO "logging: logrotate retention → ${LOG_ROTATE_WEEKS:-52} rotations"
else
    log DRY "would set logrotate retention to ${LOG_ROTATE_WEEKS:-52} weeks"
fi

if [[ "${DRY_RUN}" == false ]]; then
    cat > /etc/logrotate.d/hardened-logs <<EOF
/var/log/auth.log
/var/log/sudo.log
/var/log/fail2ban.log
/var/log/audit/audit.log
{
    rotate ${LOG_ROTATE_WEEKS:-52}
    weekly
    compress
    delaycompress
    missingok
    notifempty
    create 640 root adm
    postrotate
        /usr/lib/rsyslog/rsyslog-rotate 2>/dev/null || true
    endscript
}
EOF
    log INFO "logging: custom logrotate config written"
fi

# rsyslog

log INFO "logging: hardening rsyslog..."

if [[ "${DRY_RUN}" == false ]]; then
    if [[ -f /etc/rsyslog.conf ]]; then
        [[ -f /etc/rsyslog.conf.bak ]] || cp /etc/rsyslog.conf /etc/rsyslog.conf.bak

        if ! grep -q "auth,authpriv" /etc/rsyslog.conf; then
            echo "auth,authpriv.*   /var/log/auth.log" >> /etc/rsyslog.conf
        fi

        # don't listen on udp/tcp — we're not a log aggregator
        sed -i 's/^module(load="imudp")/#module(load="imudp")/' /etc/rsyslog.conf
        sed -i 's/^input(type="imudp"/#input(type="imudp"/' /etc/rsyslog.conf
        sed -i 's/^module(load="imtcp")/#module(load="imtcp")/' /etc/rsyslog.conf
        sed -i 's/^input(type="imtcp"/#input(type="imtcp"/' /etc/rsyslog.conf

        systemctl restart rsyslog
        log INFO "logging: rsyslog hardened (remote reception disabled)"
    fi
fi

# process accounting

if [[ "${ENABLE_PROCESS_ACCOUNTING:-true}" == true ]]; then
    log INFO "logging: enabling process accounting (acct)..."

    if [[ "${DRY_RUN}" == false ]]; then
        apt-get install -y acct > /dev/null 2>&1

        # create the accounting file if it doesn't exist yet
        mkdir -p /var/account
        touch /var/account/pacct
        accton /var/account/pacct 2>/dev/null || true

        systemctl enable acct 2>/dev/null || true
        systemctl start acct 2>/dev/null || true
        log INFO "logging: process accounting enabled (use: lastcomm, sa)"
    else
        log DRY "would install and enable process accounting"
    fi
fi

# auditd

if [[ "${ENABLE_AUDITD:-true}" == true ]]; then
    log INFO "logging: installing auditd..."

    if [[ "${DRY_RUN}" == false ]]; then
        apt-get install -y auditd audispd-plugins > /dev/null 2>&1

        AUDIT_RULES="/etc/audit/rules.d/hardening.rules"
        cat > "${AUDIT_RULES}" <<'EOF'
# auditd rules — generated by harden.sh

-D
-b 8192
-f 1

# identity files
-w /etc/passwd     -p wa -k identity
-w /etc/shadow     -p wa -k identity
-w /etc/group      -p wa -k identity
-w /etc/gshadow    -p wa -k identity
-w /etc/sudoers    -p wa -k identity
-w /etc/sudoers.d/ -p wa -k identity

# ssh config
-w /etc/ssh/sshd_config -p wa -k sshd_config
-w /root/.ssh/          -p wa -k root_ssh
-w /home/               -p wa -k user_ssh_dirs

# network and system config
-w /etc/hosts           -p wa -k network
-w /etc/hostname        -p wa -k network
-w /etc/sysctl.conf     -p wa -k sysctl
-w /etc/sysctl.d/       -p wa -k sysctl
-w /etc/crontab         -p wa -k cron
-w /etc/cron.d/         -p wa -k cron
-w /var/spool/cron/     -p wa -k cron

# login events
-w /var/log/faillog  -p wa -k logins
-w /var/log/lastlog  -p wa -k logins
-w /var/log/auth.log -p wa -k logins

# privilege escalation tools
-w /usr/bin/sudo     -p x  -k priv_esc
-w /usr/bin/su       -p x  -k priv_esc
-w /usr/bin/newgrp   -p x  -k priv_esc
-w /usr/bin/passwd   -p x  -k passwd_change

# kernel module loading
-w /sbin/insmod   -p x -k module_load
-w /sbin/rmmod    -p x -k module_load
-w /sbin/modprobe -p x -k module_load

# audit config itself
-w /etc/audit/         -p wa -k audit_config
-w /etc/audit/rules.d/ -p wa -k audit_config
-w /sbin/auditctl      -p x  -k audit_tools

# network config changes via syscalls
-a always,exit -F arch=b64 -S sethostname -S setdomainname -k network
-a always,exit -F arch=b64 -S socket -F a0=2 -k network_socket

# file deletion by non-system users
-a always,exit -F arch=b64 -S unlink -S unlinkat -S rename -S renameat \
   -F auid>=1000 -F auid!=4294967295 -k delete

# uncomment after confirming everything works — makes rules immutable until reboot:
# -e 2
EOF

        augenrules --load > /dev/null 2>&1 || auditctl -R "${AUDIT_RULES}"

        systemctl enable auditd
        systemctl restart auditd
        sleep 1

        if systemctl is-active --quiet auditd; then
            log INFO "logging: auditd running ✓"
            RULE_COUNT=$(auditctl -l 2>/dev/null | wc -l | tr -d ' ')
            log INFO "logging: ${RULE_COUNT} audit rules loaded"
        else
            log WARN "logging: auditd not running — check: journalctl -u auditd"
        fi
    else
        log DRY "would install auditd and load audit rules"
    fi
fi

# journald

log INFO "logging: hardening journald..."

if [[ "${DRY_RUN}" == false ]]; then
    [[ -f /etc/systemd/journald.conf ]] && \
        cp /etc/systemd/journald.conf /etc/systemd/journald.conf.bak

    cat > /etc/systemd/journald.conf <<'EOF'
[Journal]
# persist to disk so logs survive reboots
Storage=persistent

SystemMaxUse=500M
SystemKeepFree=100M
Compress=yes

# forward to rsyslog
ForwardToSyslog=yes

SplitMode=uid
EOF

    systemctl restart systemd-journald
    log INFO "logging: journald hardened (persistent, 500mb cap, forwarding to syslog)"
else
    log DRY "would harden journald config"
fi

echo "auditd enabled, process acct on, logrotate ${LOG_ROTATE_WEEKS:-52}wk" > /tmp/harden_note_logging

log INFO "logging hardening complete"
